theme: minima

siteConfig:
  url: https://bonzos.xyz
  author: huckingfoes
  email: author@your-domain.com
  description: bonzos etc.

themeConfig:
  nav:
    - text: Home
      link: /
    - text: About
      link: /about.html
  social:
    github: huckingfoes

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
